# Generated seed file for holiday_or_vacation_types
# This file was automatically generated from the database

holiday_or_vacation_types_data = [
  %{
    name: "Herbst",
    colloquial: "Herbstferien",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "herbst",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Herbstferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Weihnachten",
    colloquial: "Weihnachtsferien",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "weihnachten",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Weihnachtsferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Winter",
    colloquial: "Winterferien",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "winter",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Winter-/Sport-/Zeugnis-/Semester-/Faschingsferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Ostern",
    colloquial: "Osterferien",
    updated_at: ~N[2022-11-24 16:52:14],
    slug: "ostern",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Oster-/Frühjahrs-/Frühlingsferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Himmelfahrt",
    colloquial: "Himmelfahrtsferien",
    updated_at: ~N[2022-11-25 08:28:31],
    slug: "himmelfahrt",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Pfingstferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Sommer",
    colloquial: "Sommerferien",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "sommer",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Sommerferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Beweglicher Ferientag",
    colloquial: "Beweglicher Ferientag",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "beweglicher-ferientag",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.wikipedia.org/wiki/Bewegliche_Ferientage",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 7,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Wochenende",
    colloquial: "Wochenende",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "wochenende",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.wikipedia.org/wiki/Wochenende",
    default_html_class: "active",
    default_is_listed_below_month: false,
    default_display_priority: 4,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: true,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Schulschließung wegen der COVID-19-Pandemie (Corona)",
    colloquial: "Corona-Schulschließung",
    updated_at: ~N[2020-03-20 09:58:27],
    slug: "schulschliessung-wegen-der-covid-19-pandemie-corona",
    inserted_at: ~N[2020-03-20 09:58:27],
    country_location_slug: "d",
    wikipedia_url: "https://de.wikipedia.org/wiki/COVID-19-Pandemie",
    default_html_class: "danger",
    default_is_listed_below_month: true,
    default_display_priority: 20,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "1. Weihnachtstag",
    colloquial: "1. Weihnachtstag",
    updated_at: ~N[2020-03-20 10:10:32],
    slug: "1-weihnachtstag",
    inserted_at: ~N[2020-03-20 10:10:32],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "2. Weihnachtstag",
    colloquial: "2. Weihnachtstag",
    updated_at: ~N[2020-03-20 10:10:32],
    slug: "2-weihnachtstag",
    inserted_at: ~N[2020-03-20 10:10:32],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Allerheiligen",
    colloquial: "Allerheiligen",
    updated_at: ~N[2020-03-20 10:10:32],
    slug: "allerheiligen",
    inserted_at: ~N[2020-03-20 10:10:32],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Christi Himmelfahrt",
    colloquial: "Christi Himmelfahrt",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "christi-himmelfahrt",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Fronleichnam",
    colloquial: "Fronleichnam",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "fronleichnam",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Gründonnerstag",
    colloquial: "Gründonnerstag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "gruendonnerstag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Heilige Drei Könige",
    colloquial: "Heilige Drei Könige",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "heilige-drei-koenige",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Karfreitag",
    colloquial: "Karfreitag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "karfreitag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Neujahrstag",
    colloquial: "Neujahrstag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "neujahrstag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Ostermontag",
    colloquial: "Ostermontag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "ostermontag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Pfingstmontag",
    colloquial: "Pfingstmontag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "pfingstmontag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Reformationstag",
    colloquial: "Reformationstag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "reformationstag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Tag der Arbeit",
    colloquial: "Tag der Arbeit",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "tag-der-arbeit",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Tag der Deutschen Einheit",
    colloquial: "Tag der Deutschen Einheit",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "tag-der-deutschen-einheit",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Buß- und Bettag",
    colloquial: "Buß- und Bettag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "buss-und-bettag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Mariä Himmelfahrt",
    colloquial: "Mariä Himmelfahrt",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "mariae-himmelfahrt",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Frauentag",
    colloquial: "Frauentag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "frauentag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Ostersonntag",
    colloquial: "Ostersonntag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "ostersonntag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Pfingstsonntag",
    colloquial: "Pfingstsonntag",
    updated_at: ~N[2020-03-20 10:10:33],
    slug: "pfingstsonntag",
    inserted_at: ~N[2020-03-20 10:10:33],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Weltkindertag",
    colloquial: "Weltkindertag",
    updated_at: ~N[2020-03-20 10:10:35],
    slug: "weltkindertag",
    inserted_at: ~N[2020-03-20 10:10:35],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: nil,
    default_is_listed_below_month: false,
    default_display_priority: 10,
    default_is_public_holiday: false,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "Frühjahr",
    colloquial: "Frühjahrsferien",
    updated_at: ~N[2022-11-24 16:51:28],
    slug: "fruehjahr",
    inserted_at: ~N[2022-11-24 16:51:28],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Pfingsten",
    colloquial: "Pfingstferien",
    updated_at: ~N[2022-11-25 08:27:29],
    slug: "pfingsten",
    inserted_at: ~N[2022-11-25 08:27:29],
    country_location_slug: "d",
    wikipedia_url: "https://de.m.wikipedia.org/wiki/Schulferien#Pfingstferien",
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Himmelfahrt/Pfingsten",
    colloquial: "Himmelfahrt- und Pfingstferien",
    updated_at: ~N[2022-11-25 08:33:31],
    slug: "himmelfahrt-pfingsten",
    inserted_at: ~N[2022-11-25 08:33:31],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: false,
    default_is_school_vacation: true,
    default_is_valid_for_everybody: false,
    default_is_valid_for_students: true,
    default_religion_slug: nil
  },
  %{
    name: "Augsburger Hohes Friedensfest",
    colloquial: "Augsburger Friedensfest",
    updated_at: ~N[2023-12-01 00:00:00],
    slug: "augsburger-hohes-friedensfest",
    inserted_at: ~N[2023-12-01 00:00:00],
    country_location_slug: "d",
    wikipedia_url: "https://de.wikipedia.org/wiki/Augsburger_Hohes_Friedensfest",
    default_html_class: nil,
    default_is_listed_below_month: true,
    default_display_priority: 10,
    default_is_public_holiday: true,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: true,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  },
  %{
    name: "unterrichtsfreier Tag",
    colloquial: "schulfrei",
    updated_at: ~N[2023-12-01 00:00:00],
    slug: "unterrichtsfrei",
    inserted_at: ~N[2023-12-01 00:00:00],
    country_location_slug: "d",
    wikipedia_url: nil,
    default_html_class: "success",
    default_is_listed_below_month: true,
    default_display_priority: 5,
    default_is_public_holiday: true,
    default_is_school_vacation: false,
    default_is_valid_for_everybody: true,
    default_is_valid_for_students: false,
    default_religion_slug: nil
  }
]

# Initialize lookup maps
holiday_type_lookup = %{}

# Map slugs to IDs and insert
holiday_types_for_insert = Enum.map(holiday_or_vacation_types_data, fn type ->
  location_lookup = Process.get(:location_lookup, %{})
  religion_lookup = Process.get(:religion_lookup, %{})
  country_location_id = Map.get(location_lookup, type.country_location_slug)
  default_religion_id = if type.default_religion_slug, do: Map.get(religion_lookup, type.default_religion_slug)

  type
  |> Map.drop([:country_location_slug, :default_religion_slug])
  |> Map.put(:country_location_id, country_location_id)
  |> Map.put(:default_religion_id, default_religion_id)
end)

    {_, holiday_type_results} = MehrSchulferien.Repo.insert_all("holiday_or_vacation_types", holiday_types_for_insert, returning: [:id, :slug])
holiday_type_lookup = Map.merge(holiday_type_lookup, Map.new(holiday_type_results, fn %{id: id, slug: slug} -> {slug, id} end))
Process.put(:holiday_type_lookup, holiday_type_lookup)

IO.puts("Inserted #{length(holiday_or_vacation_types_data)} holiday_or_vacation_types")
