version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - riverrun
  - wintermeyer
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: ex_machina
    versions:
    - 2.6.0
  - dependency-name: bamboo
    versions:
    - 1.7.0
  - dependency-name: postgrex
    versions:
    - 0.15.8
