# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Generated by the seed generator script at 2025-05-04 16:24:58

# Load seed files in the following order
Code.require_file("seeds.d/locations_seeds.exs", __DIR__)
Code.require_file("seeds.d/religions_seeds.exs", __DIR__)
Code.require_file("seeds.d/holiday_or_vacation_types_seeds.exs", __DIR__)
Code.require_file("seeds.d/periods_seeds.exs", __DIR__)
Code.require_file("seeds.d/zip_codes_seeds.exs", __DIR__)
Code.require_file("seeds.d/addresses_seeds.exs", __DIR__)
Code.require_file("seeds.d/zip_code_mappings_seeds.exs", __DIR__)
