import Config

# Set environment
config :mehr_schulferien, :env, :prod

# Configure pdflatex path for production
config :mehr_schulferien, pdflatex_path: "/usr/bin/pdflatex"

# Production database configuration
config :mehr_schulferien, MehrSchulferien.Repo,
  # Increased pool size for production load
  pool_size: 20,
  # Optimized connection pool settings
  queue_target: 50,
  queue_interval: 1000,
  # Prepare statements for better query performance
  prepare: :named,
  # Connection timeout
  timeout: 15_000,
  # Pool timeout
  pool_timeout: 5_000,
  # Additional production optimizations
  ssl: false,
  # Enable migration locks
  migration_lock: :pg_advisory_lock

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :mehr_schulferien, MehrSchulferienWeb.Endpoint,
  url: [host: "www.mehr-schulferien.de", scheme: "https", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Check origin to prevent CSRF attacks
  check_origin: ["https://mehr-schulferien.de", "https://www.mehr-schulferien.de"],
  # Enable gzip compression for static files
  gzip: true,
  # Set cache control headers for static assets
  static_cache_control: "public, max-age=31536000"

# Increased logging level for debugging in production
# config :logger, level: :info
config :logger, level: :debug

# Set stacktrace depth to match development for detailed error reporting
config :phoenix, :stacktrace_depth, 20

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :mehr_schulferien, MehrSchulferienWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :mehr_schulferien, MehrSchulferienWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Configure Swoosh to use local Postfix via SMTP
config :mehr_schulferien, MehrSchulferien.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "localhost",
  port: 25,
  # No authentication needed for local Postfix
  auth: :never,
  # No TLS for local connection
  tls: :never,
  # Optional: set a timeout for SMTP operations (in milliseconds)
  timeout: 30_000,
  # Optional: number of retries on connection failure
  retries: 2

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
