name: Elixir CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | Node ${{ matrix.node }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        otp: [27.x]
        elixir: [1.18.3]
        node: [18.x]

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          yarn --cwd assets install

      - name: Setup database
        run: |
          mix ecto.create
          mix ecto.migrate
        env:
          MIX_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Install Chromedriver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Print Chrome and Chromedriver versions and paths
        run: |
          which chromium-browser || true
          chromium-browser --version || true
          which chromedriver || true
          chromedriver --version || true

      - name: Symlink chromedriver (if needed)
        run: |
          if [ ! -e /usr/bin/chromedriver ]; then
            sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi
          if [ ! -e /usr/bin/chromium ]; then
            sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium
          fi

      - name: Run tests
        run: |
          mix compile --warnings-as-errors
          mix format --check-formatted
          mix test
        env:
          MIX_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          WALLABY_DRIVER: chrome
          WALLABY_CHROME_BINARY: /usr/bin/chromium-browser
          WALLABY_BASE_URL: http://localhost:4002
